name: release

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: DockerHub Login
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          echo "${DOCKER_HUB_PASSWORD}" | docker login --username saltbo --password-stdin

      - name: DockerCR Login
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          DOCKERCR_PASSWORD: ${{ secrets.DOCKERCR_PASSWORD }}
        run: |
          echo "${DOCKERCR_PASSWORD}" | docker login --username yb1225@qq.com registry.cn-zhangjiakou.aliyuncs.com --password-stdin

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}